import { useMemo, useState } from 'react'
import { useFinanceStore } from '../context/FinanceContext'
import { aggregateFinance } from '../lib/finance'
import { formatCurrency, monthKey } from '../lib/format'
import { projectWealth } from '../lib/projections'
import { Card } from '../components/ui/Card'
import { NetWorthSummary } from '../components/avyo/NetWorthSummary'
import { PageHeader } from '../components/avyo/PageHeader'
import { WealthProjectionChart } from '../components/avyo/WealthProjectionChart'
const scenarios = [{ label: 'Conservador', rate: .06 }, { label: 'Moderado', rate: .10 }, { label: 'Arrojado', rate: .15 }]
export function NetWorthPage() { const { state } = useFinanceStore(); const [rate, setRate] = useState(.10); const f = useMemo(() => aggregateFinance(state, monthKey()), [state]); const points = useMemo(() => projectWealth({ initial: f.netWorth, monthlyContribution: Math.max(0, f.result), annualRate: rate, months: 12 }), [f.netWorth, f.result, rate]); return <><PageHeader eyebrow="Visão de longo prazo" title="Patrimônio" subtitle="O retrato do que você construiu, descontando o que ainda deve." /><NetWorthSummary assets={f.assetsTotal} liabilities={f.liabilitiesTotal} /><Card className="mt-5 p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-heading text-xl font-semibold">Evolução em 12 meses</h2><p className="mt-1 text-sm text-slate-500">Aporte mensal usado: {formatCurrency(Math.max(0, f.result))}</p></div><div className="flex gap-2">{scenarios.map((s) => <button key={s.label} onClick={() => setRate(s.rate)} className={`rounded-xl px-3 py-2 text-xs font-semibold ${rate === s.rate ? 'bg-violet-400/15 text-violet-200' : 'bg-white/[0.04] text-slate-500'}`}>{s.label}</button>)}</div></div><WealthProjectionChart points={points} /><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-slate-500">Simulação educativa; retornos não são garantidos.</p><strong aria-label="Patrimônio projetado" className="text-cyan-200">Em 12 meses: {formatCurrency(points.at(-1).balance)}</strong></div></Card><div className="mt-5 grid gap-4 md:grid-cols-2"><Card className="p-5"><h2 className="font-heading text-lg font-semibold">Ativos</h2>{state.assets.map((a) => <div key={a.id} className="mt-3 flex justify-between text-sm"><span className="text-slate-400">{a.name}</span><strong>{formatCurrency(a.value)}</strong></div>)}</Card><Card className="p-5"><h2 className="font-heading text-lg font-semibold">Passivos</h2>{state.liabilities.map((a) => <div key={a.id} className="mt-3 flex justify-between text-sm"><span className="text-slate-400">{a.name}</span><strong>{formatCurrency(a.value)}</strong></div>)}</Card></div></> }
