import { useState } from 'react'
import { RotateCcw, Trash2 } from 'lucide-react'
import { useFinanceStore } from '../context/FinanceContext'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { ConfirmDialog } from '../components/avyo/ConfirmDialog'
import { PageHeader } from '../components/avyo/PageHeader'
const input = 'mt-2 min-h-11 w-full rounded-xl border border-white/10 bg-white/[0.04] px-3'
export function SettingsPage() { const { state, updateProfile, resetDemo, clearAll } = useFinanceStore(); const [profile, setProfile] = useState(state.profile); const [confirm, setConfirm] = useState(null); const set = (key) => (e) => setProfile((v) => ({ ...v, [key]: e.target.type === 'number' ? Number(e.target.value) : e.target.value })); return <><PageHeader eyebrow="Sua conta local" title="Configurações" subtitle="Ajuste as premissas usadas nos cálculos do AVYO." /><Card className="p-6"><h2 className="font-heading text-xl font-semibold">Perfil financeiro</h2><form className="mt-5 grid gap-4 sm:grid-cols-2" onSubmit={(e) => { e.preventDefault(); updateProfile(profile) }}>{[['name', 'Nome', 'text'], ['income', 'Renda mensal', 'number'], ['essentialCost', 'Custo essencial', 'number'], ['monthsGoal', 'Meses de reserva', 'number'], ['payday', 'Dia do recebimento', 'number'], ['closingDay', 'Fechamento do cartão', 'number']].map(([key, label, type]) => <label key={key} className="text-sm text-slate-300">{label}<input className={input} type={type} value={profile[key]} onChange={set(key)} /></label>)}<div className="sm:col-span-2"><Button type="submit">Salvar alterações</Button></div></form></Card><Card className="mt-5 p-6"><h2 className="font-heading text-xl font-semibold">Dados deste navegador</h2><p className="mt-2 text-sm text-slate-500">Você pode recomeçar com a demonstração ou apagar tudo e voltar ao onboarding.</p><div className="mt-5 flex flex-wrap gap-3"><Button variant="secondary" onClick={() => setConfirm('reset')}><RotateCcw size={17} />Restaurar demonstração</Button><Button variant="danger" onClick={() => setConfirm('clear')}><Trash2 size={17} />Apagar tudo</Button></div></Card><ConfirmDialog open={confirm === 'reset'} title="Restaurar dados de demonstração" description="Suas alterações atuais serão substituídas pelos dados de exemplo." confirmLabel="Restaurar demonstração" onConfirm={resetDemo} onClose={() => setConfirm(null)} /><ConfirmDialog open={confirm === 'clear'} title="Apagar todos os dados" description="Esta ação remove as informações salvas neste navegador e retorna ao início." confirmLabel="Apagar meus dados" onConfirm={clearAll} onClose={() => setConfirm(null)} /></> }
