import { useMemo, useState } from 'react'
import { CalendarClock, RefreshCw, Wallet } from 'lucide-react'
import { useFinanceStore } from '../context/FinanceContext'
import { calculateUntilPayday } from '../lib/untilPayday'
import { formatCurrency, formatDate } from '../lib/format'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { PageHeader } from '../components/avyo/PageHeader'
import { planningNav, RouteNav } from '../components/avyo/RouteNav'
import { UntilPaydayWizard } from '../components/avyo/UntilPaydayWizard'

export function UntilPaydayPage() { const { state, replaceState } = useFinanceStore(); const [simulation, setSimulation] = useState(''); const save = (plan) => replaceState({ ...state, atePagamento: plan }); const result = useMemo(() => state.atePagamento ? calculateUntilPayday(state.atePagamento) : null, [state.atePagamento]); if (!result) return <><RouteNav items={planningNav} /><PageHeader eyebrow="Planejamento" title="Até receber" subtitle="Descubra um ritmo possível até o próximo dinheiro entrar." /><UntilPaydayWizard onSave={save} /></>; const after = result.remainingFree - Number(simulation || 0); return <><RouteNav items={planningNav} /><PageHeader eyebrow="Planejamento" title="Até receber" subtitle={`Seu plano vai até ${formatDate(state.atePagamento.nextPaymentDate)}.`} action={<Button variant="ghost" onClick={() => save(null)}><RefreshCw size={16} />Refazer plano</Button>} /><Card className="relative overflow-hidden p-7"><div className="absolute -right-16 -top-16 size-52 rounded-full bg-cyan-400/10 blur-3xl" /><div className="relative grid gap-7 md:grid-cols-3"><div className="md:col-span-2"><p className="text-sm text-slate-400">Ritmo diário</p><h2 className="mt-2 font-heading text-4xl font-bold text-gradient">{formatCurrency(result.dailyRhythm)}</h2><p className="mt-3 text-sm text-slate-300">por dia durante os próximos {result.days} dias.</p></div><div className="space-y-3 rounded-2xl bg-white/[0.04] p-4"><p className="flex items-center gap-2 text-sm text-slate-400"><Wallet size={16} />Livre agora</p><strong className="font-heading text-xl">{formatCurrency(result.remainingFree)}</strong><p className="flex items-center gap-2 text-xs text-slate-500"><CalendarClock size={14} />Reserva de segurança preservada</p></div></div></Card><Card className="mt-4 p-6"><h2 className="font-heading text-lg font-semibold">Teste antes de gastar</h2><label className="mt-4 block max-w-sm text-sm text-slate-300">E se gastar hoje<input type="number" min="0" value={simulation} onChange={(e) => setSimulation(e.target.value)} className="mt-2 min-h-11 w-full rounded-xl border border-white/10 bg-white/[0.04] px-3 outline-none focus:border-cyan-400/50" /></label>{simulation && <p className={`mt-4 text-sm ${after >= 0 ? 'text-cyan-200' : 'text-rose-300'}`}>Depois dessa compra, restariam {formatCurrency(after)} — cerca de {formatCurrency(result.days ? after / result.days : 0)} por dia.</p>}</Card></> }
